version: "3.7"
services:
  app:
    container_name: "db"
    image: mysql:8
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: devmentor123
      MYSQL_DATABASE: devmentor
      MYSQL_USER: "june"
      MYSQL_PASSWORD: "june123"
    ports:
      - "3306:3306"